ALTER TABLE public.health_body_entries 
ADD COLUMN IF NOT EXISTS cintura NUMERIC,
ADD COLUMN IF NOT EXISTS cuello NUMERIC,
ADD COLUMN IF NOT EXISTS pecho NUMERIC,
ADD COLUMN IF NOT EXISTS brazo_izq NUMERIC,
ADD COLUMN IF NOT EXISTS brazo_der NUMERIC,
ADD COLUMN IF NOT EXISTS antebrazo_izq NUMERIC,
ADD COLUMN IF NOT EXISTS antebrazo_der NUMERIC,
ADD COLUMN IF NOT EXISTS muneca NUMERIC,
ADD COLUMN IF NOT EXISTS cadera NUMERIC,
ADD COLUMN IF NOT EXISTS muslo_izq NUMERIC,
ADD COLUMN IF NOT EXISTS muslo_der NUMERIC,
ADD COLUMN IF NOT EXISTS pantorrilla_izq NUMERIC,
ADD COLUMN IF NOT EXISTS pantorrilla_der NUMERIC;